// @flow
import firebase from 'react-native-firebase';
// Optional flow type
import type { RemoteMessage } from 'react-native-firebase';
import {NotificationsAndroid} from "react-native-notifications"

export default async (message: RemoteMessage) => {
    // handle your message
    console.log(JSON.stringify(message))
    NotificationsAndroid.localNotification({
        title: "Local notification",
        body: "This notification was generated by the app!",
        extra: "data"
    });
    return Promise.resolve();
}